### PR TITLE
Add validation function

### PR DESCRIPTION
**Pull request by cmutel**
@sami-m-g I added these functions because the default error handling in `parse_x` gave no error context. Could you please look at this, and maybe suggest a better return type? I don't like what I have now but couldn't come up with something better.

When we have settled on the semantics we also need tests.

### CODE REVIEW

**Comment by sami-m-g** [comment]
@cmutel before going into the validation, since this pull request basically introduces 3 different changes (add documentation, modify schema rules and adds new validation) I would prefer to break it accordingly.

As for validation, the parse function currently throws an exception on schema rules validation. What is the use case we are trying to handle here?

**Comment by sami-m-g** [comment]
@cmutel, gentle ping!
Also, can you kindly update the schema docs accordingly?

**Comment by sami-m-g** [comment]
@cmutel right now, the code will throw a similar exception on schema invalidation:
```lxml.etree.DocumentInvalid: Element '{http://www.EcoInvent.org/EcoSpold01}referenceFunction', attribute 'amount': 'abc' is not a valid value of the atomic type '{http://www.EcoInvent.org/EcoSpold01}TFloatNumber'., line 17```
So why do we need this extra function when you can simply read the exception message or try and catch it accordingly?

**Comment by cmutel** [comment]
@sami-m-g I regenerated the HTML files.

You are right that in certain circumstances we can get reasonable error messages, but this isn't true for `parse_directory`, where you can only get the filename but not the line number:

Screenshot 2023-02-23 at 23 21 17

Moreover, when dealing with dirty data it is much more convenient to get a list of error instead of fixing them one by one and trying to repare the whole thing. This functionality was added because I spent 2 days debugging a > 100 MB invalid XML file over my vacation, not just for fun. Trust me, when you need it you really need it 😄.

-

**Pull request merged**
